tabs:

  fields:

    landing_page_sections:

      tab: Landing Page

      label: Landing Page Sections

      type: repeater

      form:

        fields:

            title:

                label: Section title

                type: text

                span: left

                comment: Main title for the section

            subtitle:

                label: Section subtitle

                type: text

                span: right

                comment: Subtitle for section

            layout:
                label: Section layout
                type: dropdown
                options:
                    two_columns: ['2 columns, 1 row', 'icon-pause']
                    block: ['Block', 'icon-square']
                    two_by_two: ['2 columns, 2 rows', 'icon-th-large']
                    grid: ['3 columns, 3 rows', 'icon-th']
                    card: ['Card', 'icon-list-alt']
                    quote: ['Quote', 'icon-quote-right']
                    list: ['List', 'icon-list']
                placeholder: '-- Please select a section layout --'

            link:

              label: Section link

              type: dropdown

              option: listPages

              placeholder: '-- Select a link for the feature --'
              
            features:

                label: Section features

                type: repeater

                form:

                  fields:

                    header:

                      label: Feature header

                      type: text

                    description:

                      label: Feature description

                      type: richeditor

                      size: small

                    icon:

                      label: Icon

                      type: dropdown

                      options: listIcons

                      placeholder: '-- Select an icon from the list --'

    about_page:

      tab: About Page

      label: Page header

      type: text

    about_page_description:

      tab: About Page

      label: Page description

      type: richeditor

      size: small

    about_page_sections:

      tab: About Page

      label: Page sections

      type: repeater

      form:

        fields:

            title:

                label: Section title

                type: text

                span: left

                comment: Main title for the section

            subtitle:

                label: Section subtitle

                type: text

                span: right

                comment: Subtitle for section

            layout:
                label: Section layout
                type: dropdown
                options:
                    two_columns: ['2 columns, 1 row', 'icon-pause']
                    block: ['Block', 'icon-square']
                    two_by_two: ['2 columns, 2 rows', 'icon-th-large']
                    grid: ['3 columns, 3 rows', 'icon-th']
                    card: ['Card', 'icon-list-alt']
                    quote: ['Quote', 'icon-quote-right']
                    list: ['List', 'icon-list']
                placeholder: '-- Please select a section layout --'

            features:

                label: Section features

                type: repeater

                form:

                  fields:

                    header:

                      label: Feature header

                      type: text

                    description:

                      label: Feature description

                      type: richeditor

                      size: small

                    icon:

                      label: Icon

                      type: dropdown

                      options: listIcons

                      placeholder: '-- Select an icon from the list --'
    
    guidelines_page_title:

      tab: Guidelines Page

      label: Page title

      type: text

      span: left

    guidelines_page_file:

      tab: Guidelines Page

      label: Upload file

      type: mediafinder

      mode: file

      span: right

    guidelines_page_description:

      tab: Guidelines Page

      label: Page description

      type: richeditor

      size: small

    guidelines_page_sections:

      tab: Guidelines Page

      label: Page sections

      type: repeater

      form:

        fields:

          title:

            label: Section title

            type: text

            span: left

            comment: Main title for the section

          icon:

            label: Section icon

            span: right

            type: dropdown

            options: listIcons

          description:

            label: Section description

            type: richeditor

            size: small

            span: full

            comment: Description for section

